apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: python:3.9-slim
        command: [ "sleep" ]
        args: [ "infinity" ]
        ports:
        - containerPort: 8080
        env:
        - name: POSTGRES_USERNAME
          valueFrom: 
            secretKeyRef:
              name: postgres-secret
              key: postgres-user
        - name: POSTGRES_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: postgres-secret
              key: postgres-password
        - name: DB-URL
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: postgres-url


        
---

apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30100
